import 'array-flat-polyfill';
import * as path from 'path';
import * as fs from 'fs';
import type { Reporter, TestSession } from '@web/test-runner-core';

export interface PactReporterArgs {
  /** Output directory for Pact files. Defaults to './pacts' */
  outputPath?: string;
  /** Package root dir. Defaults to cwd */
  rootDir?: string;
  /** Enable debug logging */
  debug?: boolean;
}

interface PactFile {
  consumer: { name: string };
  provider: { name: string };
  interactions: any[];
  metadata: {
    pactSpecification: { version: string };
    client?: { name: string; version: string };
  };
}

/**
 * Parse Pact files from console logs
 * Looks for messages in format: [PACT-ADAPTER] FILE <filepath> <json>
 */
function parsePactFilesFromLogs(sessions: TestSession[], debug: boolean): Map<string, PactFile> {
  const pactFiles = new Map<string, PactFile>();
  const PACT_LOG_PREFIX = '[PACT-ADAPTER] FILE ';

  for (const session of sessions) {
    if (!session.logs || session.logs.length === 0) {
      continue;
    }

    for (const logEntries of session.logs) {
      for (const logEntry of logEntries) {
        if (typeof logEntry !== 'string') {
          continue;
        }

        if (logEntry.startsWith(PACT_LOG_PREFIX)) {
          try {
            // Extract filepath and JSON from log message
            // Format: [PACT-ADAPTER] FILE ./pacts/consumer-provider.json {"consumer":...}
            const content = logEntry.slice(PACT_LOG_PREFIX.length);
            const firstSpace = content.indexOf(' ');

            if (firstSpace === -1) {
              if (debug) {
                console.warn('[PACT-REPORTER] Invalid Pact log format:', logEntry);
              }
              continue;
            }

            const filepath = content.slice(0, firstSpace);
            const jsonStr = content.slice(firstSpace + 1);
            const pactData = JSON.parse(jsonStr) as PactFile;

            // Merge with existing pact file if present (multiple tests may add interactions)
            if (pactFiles.has(filepath)) {
              const existing = pactFiles.get(filepath)!;
              existing.interactions.push(...pactData.interactions);
            } else {
              pactFiles.set(filepath, pactData);
            }

            if (debug) {
              console.log(
                `[PACT-REPORTER] Parsed Pact: ${filepath} (${pactData.interactions.length} interactions)`,
              );
            }
          } catch (error) {
            if (debug) {
              console.error('[PACT-REPORTER] Error parsing Pact log:', error, logEntry);
            }
          }
        }
      }
    }
  }

  return pactFiles;
}

/**
 * Write Pact files to disk
 */
function writePactFiles(
  pactFiles: Map<string, PactFile>,
  rootDir: string,
  debug: boolean,
): number {
  let filesWritten = 0;

  for (const [filepath, pactData] of pactFiles.entries()) {
    try {
      const fullPath = path.resolve(rootDir, filepath);
      const dir = path.dirname(fullPath);

      // Create directory if it doesn't exist
      fs.mkdirSync(dir, { recursive: true });

      // Remove duplicate interactions (same description)
      const uniqueInteractions = Array.from(
        new Map(pactData.interactions.map(i => [i.description, i])).values(),
      );
      pactData.interactions = uniqueInteractions;

      // Write Pact file
      fs.writeFileSync(fullPath, JSON.stringify(pactData, null, 2));
      filesWritten++;

      if (debug) {
        console.log(
          `[PACT-REPORTER] Wrote ${fullPath} (${pactData.interactions.length} interactions)`,
        );
      }
    } catch (error) {
      console.error(`[PACT-REPORTER] Error writing Pact file ${filepath}:`, error);
    }
  }

  return filesWritten;
}

/**
 * A Pact-format reporter for Web Test Runner
 *
 * This reporter parses Pact contract data from console logs generated by
 * the browser-side Pact adapter and writes them to disk as JSON files.
 *
 * The browser adapter logs messages in the format:
 *   [PACT-ADAPTER] FILE <filepath> <json>
 *
 * This reporter extracts those messages, parses the JSON, and writes
 * individual Pact files per provider.
 *
 * @param args Options for Pact Reporter
 *
 * @example
 * import { pactReporter } from '@web/test-runner-pact-reporter';
 *
 * export default {
 *   reporters: [
 *     pactReporter({
 *       outputPath: './pacts',
 *       debug: true,
 *     }),
 *   ],
 * };
 */
export function pactReporter({
  outputPath = './pacts',
  rootDir = process.cwd(),
  debug = false,
}: PactReporterArgs = {}): Reporter {
  return {
    onTestRunFinished({ sessions }: { sessions: TestSession[] }) {
      if (debug) {
        console.log(`[PACT-REPORTER] Processing ${sessions.length} test sessions`);
      }

      // Parse Pact files from console logs
      const pactFiles = parsePactFilesFromLogs(sessions, debug);

      if (pactFiles.size === 0) {
        if (debug) {
          console.log('[PACT-REPORTER] No Pact files found in logs');
        }
        return;
      }

      // Write Pact files to disk
      const filesWritten = writePactFiles(pactFiles, rootDir, debug);

      if (debug || filesWritten > 0) {
        console.log(`[PACT-REPORTER] ✓ Wrote ${filesWritten} Pact file(s) to ${outputPath}`);
      }
    },
  };
}
